Multiple receivers this labels review
shadrina/kotlin pull request #15
Opened 2020-10-27 04:59 UTC by shadrina

1) `this@<referencedName>` is generated for the main receiver
2) `this@<referencedName>` is generated for every additional receiver
3) If there is no main receiver, `this` is not available inside the top-level function

2020-10-30 09:19 UTC, dzharkov requested changes
предлааю обсудить этот PR

2020-10-30 09:19 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/types/expressions/LabelResolver.kt
> +            is KtNamedFunction -> {
Кажется, что-то нужно делать со свойствами тоже

2020-10-30 09:19 UTC, dzharkov commented on compiler/backend/src/org/jetbrains/kotlin/codegen/inline/InlineCodegen.kt
> +                if (labels.singleOrNull() != null) {
Не очень очевидно, что это корректно для инлайн-функций с множественными ресиверами, но наверное пока можно забить

2020-10-30 09:19 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/FunctionDescriptorUtil.java
> +            Collections.reverse(additionalReceivers);
Это не кажется очень безопасным, потому что реверснется оригинальный список

2020-10-30 09:19 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/smartcasts/IdentifierInfo.kt
> +            val receiverParameter = receiverParameters.find { it.value.type.toString() == labelName }
toString() у типа вообще не имеет никаких гарантий в общем случае

2020-11-01 11:54 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/CandidateResolver.kt
> +        if (additionalReceivers.size == candidateCall.additionalReceivers.size) {
Действительно оказалось, что проверка не нужна, так как происходит только в старом инференсе. Убрала.

2020-11-03 12:19 UTC, shadrina commented
Изменения с последнего ревью:
- Исправления насчет reverse
- Завела writable slice в BindingContext для хранения лейблов доп ресиверов: инициализирую их в `DescriptorResolver`/`FunctionDescriptorResolver`
- Поддержала генерацию this-лейблов для свойств с доп ресиверами
- Поменяла `LabelResolver` почти как договаривались: вместо `isControlExpression` добавила все-таки `isThisExpression`, чтобы сразу отсечь случаи с `super`
- Тесты на `super`, инференс с участием `this@T`
- Поняла, что нет тестов на `this@T` у классов и что они в принципе не поддержаны. Давай обсудим на следующем синке, пока просто написала тест, который валится

2020-11-17 07:50 UTC, dzharkov requested changes

2020-11-17 07:50 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/smartcasts/IdentifierInfo.kt
> +        is ClassDescriptor -> IdentifierInfo.Receiver(descriptorOfThisReceiver.thisAsReceiverParameter.value)
Кажется, здесь тоже нужно обрабатывать доп. ресиверы

2020-11-17 07:50 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/smartcasts/IdentifierInfo.kt
> +            val receiverParameters =
Я бы сделал здесь быструю проверку на случай единственного ресивера, чтобы не создавать лишние копии списков и т.д.
Это довольно часто вызываемое место

2020-11-17 07:50 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/types/expressions/LabelResolver.kt
> +            functionOrProperty.receiverTypeReference?.nameForReceiverLabel()?.let { result.add(Name.identifier(it)) }
Я бы попробовал extension `addIfNotNull`

2020-11-17 07:50 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/types/expressions/LabelResolver.kt
> +        name?.let { result.add(it) }
И тут `addIfNotNull`

2020-11-17 07:50 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/types/expressions/LabelResolver.kt
> +                    val receivers = listOfNotNull(declarationDescriptor.extensionReceiverParameter) +
Кажется, паттерн с построением списка ресиверов и затем поиска по нему по имени уже в паре мест встречался
Я бы попробовал его заэкстрактить и переиспользовать

2020-11-17 07:50 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/types/expressions/LabelResolver.kt
> +                    val receivers = listOfNotNull(declarationDescriptor.extensionReceiverParameter) +
Вообще, может быть в bindingContext для дескриптора хранить сразу мапу из имени в ресивер-параметр?

2020-12-03 12:41 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/types/expressions/LabelResolver.kt
> +            functionOrProperty.receiverTypeReference?.nameForReceiverLabel()?.let { result.add(Name.identifier(it)) }
Тут оно не совсем подходит, так как non-nullability нужна для вызова Name.identifier

2020-12-03 12:43 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/types/expressions/LabelResolver.kt
> +        name?.let { result.add(it) }
Спасибо, не знала, что такое есть. Использовала еще в паре мест выше.

2020-12-25 12:10 UTC, dzharkov requested changes

2020-12-25 12:10 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/BindingContext.java
> +import java.util.LinkedHashMap;
Кажется, unused

2020-12-25 12:10 UTC, dzharkov commented on compiler/frontend.java/src/org/jetbrains/kotlin/synthetic/JavaSyntheticPropertiesScope.kt
> +                    DescriptorFactory.createExtensionReceiverParameterForCallable(descriptor, receiverType, Annotations.EMPTY, false),
Большая часть вызовов createExtensionReceiverParameterForCallable c false-аргументом
Я бы добавил перегрузку с этим значением по умолчанию

2020-12-25 12:10 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/DescriptorResolver.java
> +        Map<KtTypeReference, KotlinType> nonNullReceiverTypeReferencesToTypes = new HashMap<>();
Я бы использовал LinkedHashMap, потому что она обеспечит стабильный порядок и это будет легче в будущем дебажить

2020-12-25 12:10 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/DescriptorResolver.java
> +        trace.record(DESCRIPTOR_TO_NAMED_RECEIVERS, getter, receiverToLabelMap);
Мне кажется писать тот же слайс для геттеров нет особой необходимости
В том месте, где он используется, можно проверить, что у нас тут геттер и достать родительскую декларацию

2020-12-25 12:10 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/FunctionDescriptorResolver.kt
> +        additionalReceivers.reversed().forEachIndexed { i, additionalReceiver ->
Я бы воспользовался zip/zipWith вместо махинаций с индексами

2020-12-25 12:10 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/FunctionDescriptorUtil.java
> +            implicitReceivers.addAll(additionalReceivers);
Я бы заинлайнил переменную

2020-12-25 12:10 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/smartcasts/IdentifierInfo.kt
> +    val receiverParameter = receiverToLabelEntries?.find {
Кажется, здесь бы больше пригодилась инвертированная мапа (или две), чтобы не бегать за линию от числа ресиверов

2021-01-18 08:02 UTC, shadrina commented on compiler/frontend.java/src/org/jetbrains/kotlin/synthetic/JavaSyntheticPropertiesScope.kt
> +                    DescriptorFactory.createExtensionReceiverParameterForCallable(descriptor, receiverType, Annotations.EMPTY, false),
Поправила

2021-01-18 08:21 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/DescriptorResolver.java
> +        Map<KtTypeReference, KotlinType> nonNullReceiverTypeReferencesToTypes = new HashMap<>();
Поправила

2021-01-18 08:21 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/DescriptorResolver.java
> +        trace.record(DESCRIPTOR_TO_NAMED_RECEIVERS, getter, receiverToLabelMap);
Поправила

2021-01-18 08:29 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/FunctionDescriptorUtil.java
> +            implicitReceivers.addAll(additionalReceivers);
Поправила

2021-01-18 12:12 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/FunctionDescriptorResolver.kt
> +        additionalReceivers.reversed().forEachIndexed { i, additionalReceiver ->
Поправила

2021-01-19 05:01 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/FunctionDescriptorResolver.kt
> +        additionalReceivers.reversed().forEachIndexed { i, additionalReceiver ->
Поправила

2021-01-19 15:35 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/smartcasts/IdentifierInfo.kt
> +            val receiverParameters =
Поправила

2021-01-19 16:30 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/smartcasts/IdentifierInfo.kt
> +    val receiverParameter = receiverToLabelEntries?.find {
Сделала свою структуру

2021-04-12 05:07 UTC, closed without merging