Multiple receivers resolution review
shadrina/kotlin pull request #16
Opened 2020-10-27 05:22 UTC by shadrina

2020-10-27 05:25 UTC, shadrina commented on compiler/resolution/src/org/jetbrains/kotlin/resolve/calls/components/ResolutionParts.kt
> +            } ?: run {
You commented in the previous PR:

> I'd just return null here (with ?: return null), but reported an error on the call-site
So, the responsibility of the function would be limited and clear

The problem here is that I will lose the information about the missing receiver if I report an error outside of this function.

2020-10-30 08:35 UTC, dzharkov requested changes

2020-10-30 08:35 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/model/ResolvedCallImpl.java
> +        return Collections.emptyList();
Можно удалить геттер?

2020-10-30 08:35 UTC, dzharkov commented on core/descriptors/src/org/jetbrains/kotlin/types/TypeUtils.kt
> +fun KotlinType.hasTypeArguments(): Boolean = arguments.any { it.type.isTypeParameter() || it.type.hasTypeArguments() }
Имя функции мне кажется неудачным
Я бы назвал её `containsTypeParameter` и для реализации воспользовался бы `TypeUtils.contains`

2020-11-01 10:22 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/model/ResolvedCallImpl.java
> +        return Collections.emptyList();
К сожалению, нельзя. В `psi2ir` используется именно интерфейс `ResolvedCall`. `ResolvedCallAtom` используется только для проверки кандидата, и затем с помощью `KotlinToResolvedCallTransformer` трансформируется в `NewResolvedCallImpl`.

2020-11-13 09:58 UTC, shadrina commented on compiler/resolution/src/org/jetbrains/kotlin/resolve/calls/components/ResolutionParts.kt
> +                val candidateReceiverType = candidateReceiver.receiverValue.type
Сейчас вдруг появился вопрос, а может ли здесь быть typeParameter?

2020-12-25 12:23 UTC, dzharkov approved these changes

2020-12-25 12:23 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/model/ResolvedCallImpl.java
> +        return Collections.emptyList();
Сорри, я не очень понял
Этот метод не должен вызываться?

2020-12-25 12:23 UTC, dzharkov commented on compiler/testData/diagnostics/tests/extensions/additionalReceivers/functions/manyReceivers.kt
> +class A {
Я бы добавил тестов с явным главным ресивером и парой дополнительных неявных.

2020-12-25 12:23 UTC, dzharkov commented on compiler/resolution/src/org/jetbrains/kotlin/resolve/calls/components/ResolutionParts.kt
> +        fun KotlinType.prepared(): KotlinType = if (containsTypeParameter()) replaceArgumentsWithStarProjections() else this
Я бы сделал её приватной нелокальной функцией

2020-12-25 12:23 UTC, dzharkov commented on compiler/resolution/src/org/jetbrains/kotlin/resolve/calls/components/ResolutionParts.kt
> +                if (expectedReceiverType.isTypeParameter()) expectedReceiverType.supertypes().first()
Кажется, в другом PR есть функция, которая это делает

2020-12-25 12:23 UTC, dzharkov commented on compiler/resolution/src/org/jetbrains/kotlin/resolve/calls/components/ResolutionParts.kt
> +                val candidateReceiverType = candidateReceiver.receiverValue.type
Может, наверное, но кажется это не страшно

2021-01-16 18:57 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/model/ResolvedCallImpl.java
> +        return Collections.emptyList();
Я накопила вопросов на понедельник. Давай голосом расскажу.

2021-01-19 06:46 UTC, shadrina commented on compiler/resolution/src/org/jetbrains/kotlin/resolve/calls/components/ResolutionParts.kt
> +                if (expectedReceiverType.isTypeParameter()) expectedReceiverType.supertypes().first()
Объединила

2021-04-12 05:08 UTC, closed without merging