Object receivers for classes review
shadrina/kotlin pull request #17
Opened 2020-10-27 09:59 UTC by shadrina

2020-10-30 07:48 UTC, dzharkov requested changes

2020-10-30 07:48 UTC, dzharkov commented on compiler/psi/src/org/jetbrains/kotlin/psi/KtPureClassOrObject.java
> +    List<KtExpression> getAdditionalReceiverObjects();
Я бы назвал это `getAdditionalReceiverExpressions`

2020-10-30 07:48 UTC, dzharkov commented on compiler/psi/src/org/jetbrains/kotlin/psi/KtClassOrObject.kt
> +        var child = firstChild
Попробуй findChildByType

2020-10-30 07:48 UTC, dzharkov commented on compiler/psi/src/org/jetbrains/kotlin/parsing/KotlinParsing.java
> +        boolean additionalReceiverObjectParsed = tryParseAdditionalReceiverObject();
то же самое про object -> expression

2020-10-30 07:48 UTC, dzharkov commented on compiler/psi/src/org/jetbrains/kotlin/parsing/KotlinParsing.java
> +        if (!additionalReceiverObjectParsed) {
Может быть стоит просто сделать lookahead(1) на круглую скобку?

2020-10-30 07:48 UTC, dzharkov commented on compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/NameProvider.kt
> +    fun nameForAdditionalReceiverObject(index: Int): Name
то же самое про object -> expression

2020-10-30 07:48 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/DescriptorResolver.java
> +    public KotlinType getAdditionalReceiverObjectKotlinType(
то же самое про object -> expression
и везде, где используется слово "object" :)

2020-10-30 07:48 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/lazy/descriptors/LazyClassDescriptor.java
> +    private void getAdditionalReceiverObjects() {}
Кажется, бесполезный метод

2020-10-30 07:48 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/lazy/descriptors/LazyClassDescriptor.java
> +
избыточное изменение

2020-10-30 07:50 UTC, dzharkov commented on compiler/testData/diagnostics/tests/extensions/additionalReceiverObjects/classes/simple.fir.kt
> +with<A> fun f() {}
Я бы проверил, что внутри `f` доступен ресивер для `A`

2020-10-30 07:53 UTC, dzharkov commented on compiler/testData/codegen/box/extensionClasses/additonalReceiverObjects/simple.kt
> +class A {
Вообще предлагаю делать чуть более покрывающие тесты:
- проперти 
- обычные функции с параметрами
- generic-функции
- вызов extension на дополнительном ресивере
- inner конструкторы на дополнительном ресивере
- ещё что-нибудь :)

2020-11-10 05:47 UTC, shadrina commented on compiler/testData/codegen/box/extensionClasses/additonalReceiverObjects/simple.kt
> +class A {
Этот тест расширила, тем не менее, КМК, тестов на классы и (особенно) проперти у меня в принципе мало. Залью отдельным PR.

2020-11-17 08:23 UTC, dzharkov requested changes

2020-11-17 08:23 UTC, dzharkov commented on compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ClassGenerator.kt
> +                context.symbolTable.nameProvider.nameForAdditionalReceiverExpression(fieldIndex),
Нужно ли инкрементить `fieldIndex`?

2020-11-17 08:23 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/lazy/descriptors/LazyClassDescriptor.java
> +        LexicalScope scopeForMemberDeclarationResolution = resolutionScopesSupport.getScopeForMemberDeclarationResolution().invoke();
А какие для этих ресиверов будут имена меток?
Возможно стоит это записать в список вопросов

2020-11-26 11:39 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/lazy/descriptors/LazyClassDescriptor.java
> +        LexicalScope scopeForMemberDeclarationResolution = resolutionScopesSupport.getScopeForMemberDeclarationResolution().invoke();
Да, как раз про это спрашивала выше.

2020-12-25 12:54 UTC, dzharkov requested changes

2020-12-25 12:54 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/DescriptorResolver.java
> +    public KotlinType getAdditionalReceiverExpressionKotlinType(
У этого метода один юзадж и тривиальное содержимое, может быть его заинлайнить?

2020-12-25 12:54 UTC, dzharkov commented on compiler/testData/codegen/box/extensionClasses/additonalReceiverExpressions/simple.kt
> +fun box(): String = "OK"
Кажется, нужно больше бокс тестов

2021-04-12 05:08 UTC, closed without merging