Prototype of context receivers
shadrina/kotlin pull request #21
Opened 2021-06-21 09:32 UTC by shadrina

2021-07-01 08:11 UTC, dzharkov requested changes
Остальное буду ревьюить в новом PR

2021-07-01 08:11 UTC, dzharkov commented on compiler/psi/src/org/jetbrains/kotlin/parsing/KotlinParsing.java
> +    private void parseContextReceiver() {
(minor) I'd call it `parseContextReceivers`

2021-07-01 08:11 UTC, dzharkov commented on compiler/psi/src/org/jetbrains/kotlin/parsing/KotlinParsing.java
> +    private void parseContextReceiver() {
or even ContextReceiverList

2021-07-01 08:11 UTC, dzharkov commented on compiler/psi/src/org/jetbrains/kotlin/psi/KtContextReceiver.kt
> +class KtContextReceiver : KtElementImplStub<KotlinPlaceHolderStub<KtContextReceiver>> {
Probably `KtContextReceiverList` suits better

2021-07-01 08:11 UTC, dzharkov commented on compiler/psi/src/org/jetbrains/kotlin/psi/KtNamedFunction.java
> +    public List<KtTypeReference> getContextReceiverTypeReferences() {
I'd better put this logic to `KtContextReceiverList` to avoid duplication
See org.jetbrains.kotlin.psi.KtNamedFunction#getValueParameters

2021-07-01 08:11 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/lazy/descriptors/ClassResolutionScopesSupport.kt
> +            classDescriptor.contextReceivers + classDescriptor.thisAsReceiverParameter,
I haven't seen the following commits, but we need to make sure that context receivers are not being added as normal receivers to scopes

2021-07-01 08:11 UTC, dzharkov commented on core/descriptors/src/org/jetbrains/kotlin/resolve/scopes/receivers/ExtensionClassReceiver.kt
> +class ExtensionClassReceiver(
I'd better call it `ContextClassReceiver`

2021-07-01 08:11 UTC, dzharkov commented on core/descriptors/src/org/jetbrains/kotlin/resolve/scopes/receivers/ExtensionReceiver.java
> +    private final boolean isContextReceiver;
I'd better add a different class for context receivers from callable declarations

2021-07-01 08:11 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/BindingContext.java
> +    WritableSlice<DeclarationDescriptor, LinkedHashMap<ReceiverParameterDescriptor, String>> DESCRIPTOR_TO_NAMED_RECEIVERS = Slices.createSimpleSlice();
Please, use just `Map` instead of `LinkedHashMap`

2021-07-01 08:11 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/BindingContext.java
> +    WritableSlice<DeclarationDescriptor, LinkedHashMap<ReceiverParameterDescriptor, String>> DESCRIPTOR_TO_NAMED_RECEIVERS = Slices.createSimpleSlice();
BTW, why is it not a map from Name to ReceiverParameterDescriptor?

2021-07-01 08:11 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/smartcasts/IdentifierInfo.kt
> +    val receiverToLabelMap = bindingContext.get(
I'd just add early return in case `labelName` is null

2021-07-01 08:11 UTC, dzharkov commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/smartcasts/IdentifierInfo.kt
> +    labelName: String? = null
Looks like `labelName` is not null only for the KtThisExpression case
So, I would just handle that logic there

2021-07-01 08:11 UTC, dzharkov commented on compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/StatementGenerator.kt
> +                } ?: referenceTarget.extensionReceiverParameter ?: TODO("No receiver: $referenceTarget")
Please, avoid using `TODO` in "production-ready" code
`error` may work here

2021-07-01 08:11 UTC, dzharkov commented on compiler/psi/src/org/jetbrains/kotlin/parsing/KotlinParsing.java
> +            contextReceiverList.done(CONTEXT_RECEIVER_LIST);
Not crucial here, but it would be nice to have new new element types (CONTEXT_RECEIVER_LIST) and parsing rules for them in the same commit :)

2021-07-12 14:15 UTC, shadrina commented on compiler/psi/src/org/jetbrains/kotlin/parsing/KotlinParsing.java
> +    private void parseContextReceiver() {
It is called contextReceiverList in the last version

2021-07-12 14:15 UTC, shadrina commented on compiler/psi/src/org/jetbrains/kotlin/psi/KtContextReceiver.kt
> +class KtContextReceiver : KtElementImplStub<KotlinPlaceHolderStub<KtContextReceiver>> {
It is called KtContextReceiverList in the last version

2021-08-14 15:14 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/BindingContext.java
> +    WritableSlice<DeclarationDescriptor, LinkedHashMap<ReceiverParameterDescriptor, String>> DESCRIPTOR_TO_NAMED_RECEIVERS = Slices.createSimpleSlice();
Because we can have multiple ReceiverParameterDescriptors with the same Name

2021-09-18 12:23 UTC, shadrina commented on compiler/psi/src/org/jetbrains/kotlin/parsing/KotlinParsing.java
> +            contextReceiverList.done(CONTEXT_RECEIVER_LIST);
🙂

2021-09-27 09:28 UTC, shadrina commented on compiler/psi/src/org/jetbrains/kotlin/psi/KtNamedFunction.java
> +    public List<KtTypeReference> getContextReceiverTypeReferences() {
Fixed, thanks!

2021-09-27 10:36 UTC, shadrina commented on core/descriptors/src/org/jetbrains/kotlin/resolve/scopes/receivers/ExtensionReceiver.java
> +    private final boolean isContextReceiver;
Created `ContextReceiver` class.

2021-09-27 11:47 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/smartcasts/IdentifierInfo.kt
> +    val receiverToLabelMap = bindingContext.get(
I added 2 overloads, one of which has non-nullable `labelName` parameter.

2021-09-27 11:47 UTC, shadrina commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/smartcasts/IdentifierInfo.kt
> +    labelName: String? = null
Thank you, fixed.

2021-10-21 20:00 UTC, closed without merging